GuguDadah/GuguDadah/Pages/AdminArea.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using GuguDadah.Data;
using System.IO;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.Authentication;

namespace GuguDadah.Pages {

    [Authorize(Roles = "Admin")]
    public class AdminArea : PageModel {

    }
}

GuguDadah/GuguDadah/Pages/AdminOverview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

using GuguDadah.Data;
using System.IO;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.Authentication;
using GuguDadah.Includes;

namespace GuguDadah.Pages {

    [Authorize(Roles = "Admin")]
    public class AdminOverview : PageModel {

        public List<Client> ClientsList { get; set; }

        public List<Professional> ProfessionalsList { get; set; }

        public List<Work> WorksList { get; set; }

        private readonly AppDbContext dbContext;

        public AdminOverview(AppDbContext context) {

            dbContext = context;
        }

        public IActionResult OnGet() {

            return Unauthorized();
        }
            
        // método chamado quando se carrega no botão lista de clientes
        public ActionResult OnGetListOfClients() {

            // traz os clientes da BD, ordenados pelo username
            var query = (from p in dbContext.Clients
                         orderby p.UserName
                         select p).ToList();

            ClientsList = new List<Client>();

            // vai buscar o conteúdo de toda a query
            foreach (var item in query) {

                string displayStatus = null;
                if (item.Status.Equals("N")) displayStatus = "Normal";
                if (item.Status.Equals("G")) displayStatus = "Golden";

                // coloca numa lista que será lida pela view
                ClientsList.Add(new Client() {
                    UserName = item.UserName,
                    Name = item.Name,
                    Contact = item.Contact,
                    Email = item.Email,
                    Avatar = item.Avatar,
                    Status = displayStatus
                });
            }

            return Page();
        }

        // método chamado quando se carrega no botão lista de profissionais
        public ActionResult OnGetListOfProfessionals() {

            // traz os profissionais da BD, ordenados pelo username
            var query = (from p in dbContext.Professionals
                         orderby p.UserName
                         select p).ToList();

            ProfessionalsList = new List<Professional>();

            // vai buscar o conteúdo de toda a query
            foreach (var item in query) {

                // coloca numa lista que será lida pela view
                ProfessionalsList.Add(new Professional() {
                    UserName = item.UserName,
                    Contact = item.Contact,
                    Email = item.Email,
                    Avatar = item.Avatar,
                    Rating = item.Rating,
                    Shift = item.Shift,
                    RegistrationDate = item.RegistrationDate,
                    Name = item.Name
                });
            }

            return Page();
        }

        // método chamado quando se carrega no botão lista de trabalhos
        public ActionResult OnGetListOfWorks() {

            // traz os trabalhos da BD, ordenados pelo data
            var query = (from work in dbContext.Works
                         join pro in dbContext.Professionals on work.Professional.UserName equals pro.UserName
                         join cli in dbContext.Clients on work.Client.UserName equals cli.UserName
                         orderby work.Date
                         select new { work, pro, cli }).ToList();

            WorksList = new List<Work>();

            // vai buscar o conteúdo de toda a query
            foreach (var item in query) {

                string displayStatus = null;
                string displayPayment = null;

                // converte os carateres em strings user-friendly para a view
                if (item.work.Status.Equals("O")) displayStatus = "Oferta";
                if (item.work.Status.Equals("P")) displayStatus = "Pendente";
                if (item.work.Status.Equals("C")) displayStatus = "Completo";
                if (item.work.Payment.Equals("S")) displayPayment = "Pago";
                if (item.work.Payment.Equals("N")) displayPayment = "Não Pago";

                // coloca numa lista que será lida pela view
                WorksList.Add(new Work() {
                    Id = item.work.Id,
                    Address = item.work.Address,
                    Client = item.cli,
                    Professional = item.pro,
                    Cost = item.work.Cost,
                    Date = item.work.Date,
                    Duration = item.work.Duration,
                    Payment = displayPayment,
                    Status = displayStatus,
                    Rating = item.work.Rating,
                    Type = item.work.Type
                });
            }

            return Page();
        }

        // método chamado quando se carrega no botão marcar como golden. Traz o username do cliente...
        public IActionResult OnPostMarkAsGolden(string username) {

            // vai buscar o cliente à BD
            var client = dbContext.Clients.FirstOrDefault(m => m.UserName.Equals(username));

            // muda o estatuto da cliente
            client.Status = "G";

            // guarda o cliente na BD
            dbContext.SaveChanges();

            return RedirectToPage("/AdminOverview", "ListOfClients").WithSuccess("Admin", "Cliente marcado como golden com sucesso.", "2000");
        }

        // método chamado quando se carrega no botão marcar como normal. Traz o username do cliente...
        public IActionResult OnPostMarkAsNormal(string username) {

            // vai buscar o cliente à BD
            var client = dbContext.Clients.FirstOrDefault(m => m.UserName.Equals(username));

            // muda o estatuto do cliente
            client.Status = "N";

            // guarda o cliente na BD
            dbContext.SaveChanges();

            return RedirectToPage("/AdminOverview", "ListOfClients").WithSuccess("Admin", "Cliente marcado como normal com sucesso.", "2000");
        }

        // método chamado quando se carrega no botão marcar como pago. Traz o id do trabalho...
        public IActionResult OnPostMarkAsPaid(int id) {

            // vai buscar o trabalho à BD
            var work = dbContext.Works.FirstOrDefault(m => m.Id.Equals(id));

            // muda o estado do pagamento para SIM
            work.Payment = "S";

            // guarda o trabalho na BD
            dbContext.SaveChanges();

            return RedirectToPage("/AdminOverview", "ListOfWorks").WithSuccess("Admin", "O trabalho foi marcado como pago com sucesso.", "2000");
        }

        // método chamado quando se carrega no botão apagar profissional. Traz o username do profissional...
        public IActionResult OnPostDeleteProfessional(string username) {

            // vai buscar o profissional à BD
            var pro = dbContext.Professionals.FirstOrDefault(m => m.UserName.Equals(username));

            // remove o profissional
            dbContext.Professionals.Remove(pro);

            // guarda as alterações
            dbContext.SaveChanges();

            return RedirectToPage("/AdminOverview", "ListOfProfessionals").WithSuccess("Admin", "O profissional foi removido com sucesso.", "2000");
        }

        // método chamado quando se carrega no botão apagar cliente. Traz o username do cliente...
        public IActionResult OnPostDeleteClient(string username) {

            // vai buscar o cliente à BD
            var cli = dbContext.Clients.FirstOrDefault(m => m.UserName.Equals(username));

            // remove o cliente
            dbContext.Clients.Remove(cli);

            // guarda as alterações
            dbContext.SaveChanges();

            return RedirectToPage("/AdminOverview", "ListOfClients").WithSuccess("Admin", "O cliente foi removido com sucesso.", "2000");
        }

    }
}

GuguDadah/GuguDadah/Pages/Babysitters.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using GuguDadah.Data;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

namespace GuguDadah.Pages {

    public class Babysitters : PageModel {

        private readonly AppDbContext dbContext;

        public Babysitters(AppDbContext context) {

            dbContext = context;
        }

        public List<Professional> list = new List<Professional>();

        public int ShowBabysitters { get; set; }

        public int ChooseBabysitters { get; set; }

        public IActionResult OnGet() {

            return Unauthorized();
        }

        // método que é chamado quando o cliente quer ver os babysitters do sistema
        [Authorize(Roles = "Client")]
        public ActionResult OnGetShowBS() {

            // define que devem ser apenas mostrados os babysitters sem botão pra escolher
            ShowBabysitters = 1;

            // vai buscar todos os profissionais à BD
            var query = (from p in dbContext.Professionals
                         orderby p.Rating descending
                         select p).ToList();

            // itera pela query e adiciona à lista que será lida pela view
            foreach (var item in query) {

                list.Add(new Professional() {
                    UserName = item.UserName,
                    Name = item.Name,
                    Contact = item.Contact,
                    Email = item.Email,
                    Avatar = item.Avatar,
                    Shift = item.Shift,
                    Rating = item.Rating
                });
            }

            return Page();
        }

        // método que é chamado quando o cliente quer escolher um babysitter
        [Authorize(Roles = "Client")]
        public ActionResult OnGetChooseBS() {

            // define que devem ser mostrados os babysitters do turno e um botão para escolher
            ChooseBabysitters = 1;

            // recebe o custo calculado na página anterior (página do agendamento)
            Object cost = TempData["cost"];

            // manda o custo para a página seguinte (página do pagamento)
            TempData["cost2"] = cost;

            // recebe a hora de início do trabalho introduzido na página anterior;
            TimeSpan TimeScheduled = JsonConvert.DeserializeObject<TimeSpan>(TempData["time"].ToString());

            // turno da noite
            TimeSpan NShiftStart = new TimeSpan(0, 0, 0);
            TimeSpan NShiftEnd = new TimeSpan(7, 59, 59);

            // turno da manhã
            TimeSpan MShiftStart = new TimeSpan(8, 0, 0);
            TimeSpan MShiftEnd = new TimeSpan(15, 59, 59);

            // turno da tarde
            TimeSpan TShiftStart = new TimeSpan(16, 0, 0);
            TimeSpan TShiftEnd = new TimeSpan(23, 59, 59);

            string ShiftFilter = null;

            // vê se a hora de início se enquadra no turno da manhã
            if (TimeScheduled >= MShiftStart && TimeScheduled <= MShiftEnd) {
                ShiftFilter = "M";
            }

            // vê se a hora de início se enquadra no turno da tarde
            if (TimeScheduled >= TShiftStart && TimeScheduled <= TShiftEnd) {
                ShiftFilter = "T";
            }

            // vê se a hora de início se enquadra no turno da noite
            if (TimeScheduled >= NShiftStart && TimeScheduled <= NShiftEnd) {
                ShiftFilter = "N";
            }

            // vai buscar os profissionais à BD que têm o turno definido
            var query = (from p in dbContext.Professionals
                         orderby p.Rating descending
                         where p.Shift == ShiftFilter
                         select p).ToList();

            // itera pela query e adiciona os profissionais à lista que será mostrada na view
            foreach (var item in query) {

                list.Add(new Professional() {
                    UserName = item.UserName,
                    Name = item.Name,
                    Avatar = item.Avatar,
                    Rating = item.Rating,
                    RegistrationDate = item.RegistrationDate,
                    Presentation = item.Presentation
                });
            }

            return Page();

        }
    }
}

GuguDadah/GuguDadah/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GuguDadah.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GuguDadah/GuguDadah/Pages/GPSLocation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

using GuguDadah.Data;
using System.IO;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.Authentication;

namespace GuguDadah.Pages {

    [Authorize(Roles = "Professional")]
    public class GPSLocation : PageModel {

        public string Address{ get; set; }

        public IActionResult OnGet() {

            return Unauthorized();
        }

        // este método é chamado quando se carrega no botão localização e atribui o endereço à variável local.
        public void OnPostGPSLocation(string address) {

            Address = address;
        }

    }
}

GuguDadah/GuguDadah/Pages/Payment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

using GuguDadah.Data;
using System.IO;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.Authentication;
using Newtonsoft.Json;
using GuguDadah.Includes;

namespace GuguDadah.Pages {

    [Authorize(Roles = "Client")]
    public class Payment : PageModel {

        [Required]
        [BindProperty]
        [Display(Name = "Método de Pagamento")]
        public string PaymentType { get; set; }

        [Required]
        [BindProperty]
        [Display(Name = "Preço")]
        public double Cost { get; set; }

        private readonly AppDbContext dbContext;

        public Payment(AppDbContext context) {

            dbContext = context;
        }

        public IActionResult OnGet() {

            return Unauthorized();
        }

        // método chamado quando escolhe o babysitter... Recebe o username do profissional...
        public void OnPostPaymentEnter(string username) {

            // guarda o profisional num buffer
            TempData["proUsername"] = username;

            // recebe o custo da página anterior
            Cost = (double) TempData["cost2"];

        }

        // método chamado quando o utilizador paga
        public IActionResult OnPostChoosedPayment() {

            TryUpdateModelAsync(this);

            // recebe todo o trabalho
            Work work;
            work = JsonConvert.DeserializeObject<Work>(TempData["tempWork"].ToString());

            // se for null, alguma coisa de errado aconteceu
            if (work == null) return Page();

            // recebe o profissional anteriormente guardado e vai buscá-lo à BD
            Professional professional = dbContext.Professionals.FirstOrDefault(m => m.UserName.Equals(TempData["proUsername"]));

            // vai buscar o cliente à BD
            Client Client = dbContext.Clients.FirstOrDefault(m => m.UserName.Equals(User.Identity.Name));

            // define o pagamento
            if (PaymentType.Equals("money")) work.Payment = "N";

            if (PaymentType.Equals("card")) work.Payment= "S";

            work.Client = Client;
            work.Professional = professional;

            // envia email
            Email email = new Email();
            string destination = professional.Email;
            string subject = "GuguDadah - Oferta recebida";
            string body = "Recebeu uma oferta de trabalho. Por favor, consulte o site.";

            email.SendEmail(destination, subject, body);

            // adiciona o novo trabalho
            dbContext.Works.Add(work);

            // guarda as alterações
            dbContext.SaveChanges();

            return RedirectToPage("/UserArea", "ClientLoggedIn").WithSuccess("Agendamento", "efetuado com sucesso.", "3000");
        }

        public IActionResult OnGetCancelSchedule() {

            return RedirectToPage("/UserArea", "ClientLoggedIn").WithDanger("Agendamento", "cancelado.", "3000");
        }
    }
}

GuguDadah/GuguDadah/Pages/AdminOverview.cshtml
@page
@model GuguDadah.Pages.AdminOverview
@{
    ViewData["Title"] = "Visão Geral";

}

@section head
    {
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />

}

@section Scripts
    {

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script>
        $('#clients').DataTable({
            paging: true,
            "columnDefs": [{
                "targets": 5,
                "searchable": false,
                "orderable": false,
                "visible": true
            }],
            "language": {
                "lengthMenu": "Mostrar _MENU_ linhas por página",
                "zeroRecords": "Nada encontrado.",
                "info": "A mostrar a página _PAGE_ de _PAGES_",
                "infoEmpty": "Sem linhas disponíveis",
                "infoFiltered": "(filtrado de _MAX_ linhas)",
                "search": "Procurar: ",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Seguinte"
                }
            }
        });
    </script>

    <script>
        $('#works').DataTable({
            paging: true,
            "columnDefs": [{
                "targets": 5,
                "searchable": false,
                "orderable": false,
                "visible": true
            }],
            "language": {
                "lengthMenu": "Mostrar _MENU_ linhas por página",
                "zeroRecords": "Nada encontrado.",
                "info": "A mostrar a página _PAGE_ de _PAGES_",
                "infoEmpty": "Sem linhas disponíveis",
                "infoFiltered": "(filtrado de _MAX_ linhas)",
                "search": "Procurar: ",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Seguinte"
                }
            }
        });
    </script>
    <script>
        $('#professionals').DataTable({
            paging: true,
            "columnDefs": [{
                "targets": 7,
                "searchable": false,
                "orderable": false,
                "visible": true
            }],
            "language": {
                "lengthMenu": "Mostrar _MENU_ linhas por página",
                "zeroRecords": "Nada encontrado.",
                "info": "A mostrar a página _PAGE_ de _PAGES_",
                "infoEmpty": "Sem linhas disponíveis",
                "infoFiltered": "(filtrado de _MAX_ linhas)",
                "search": "Procurar: ",
                "paginate": {
                    "previous": "Anterior",
                    "next": "Seguinte"
                }
            }
        });
    </script>
}

@if (Model.ClientsList != null) {

    <h4>Lista de Clientes</h4>
    <hr />

    <div class="container-fluid">
        <div class="table-responsive">
            <table id="clients" class="row-border" style="width:100%">
                <thead>
                    <tr>
                        <th class="text-center"><span>Nickname</span></th>
                        <th class="text-center"><span>Nome</span></th>
                        <th class="text-center"><span>Email</span></th>
                        <th class="text-center"><span>Contacto</span></th>
                        <th class="text-center"><span>Estatuto</span></th>
                        <th class="text-center">Remover/Estatuto</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ClientsList) {
                        <tr>
                            <td class="text-center">
                                <img src="data:image/jpeg;base64,@System.Convert.ToBase64String(item.Avatar)" width="50" height="50" alt="" />
                                <span><strong> @item.UserName</strong></span>
                            </td>
                            <td class="text-center">@item.Name</td>
                            <td class="text-center">
                                <span>@item.Email</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Contact</span>
                            </td>
                            <td class="text-center">
                                <span class="label label-default">@item.Status</span>
                            </td>
                            <td class="text-center" style="width: 15%;">

                                <form asp-page-handler="DeleteClient" asp-route-username="@item.UserName" method="post" style="display: inline;">
                                    <button type="submit" class="myButton">
                                        <span class="fa-stack">
                                            <i class="fa fa-minus-square fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </button>
                                </form>

                                @if (item.Status.Equals("Normal")) {
                                    <form asp-page-handler="MarkAsGolden" asp-route-username="@item.UserName" method="post" style="display: inline;">
                                        <button type="submit" class="myButton">
                                            <span class="fa-stack">
                                                <i class="fa fa-google fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </button>
                                    </form>
                                }
                                else {
                                    <form asp-page-handler="MarkAsNormal" asp-route-username="@item.UserName" method="post" style="display: inline;">
                                        <button type="submit" class="myButton">
                                            <span class="fa-stack">
                                                <i class="fa fa-angle-left fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </button>
                                    </form>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

@if (Model.ProfessionalsList != null) {

    <h4>Lista de Profissionais</h4>
    <hr />

    <div class="container-fluid">
        <div class="table-responsive">
            <table id="professionals" class="row-border" style="width:100%">
                <thead>
                    <tr>
                        <th class="text-center"><span>Nickname</span></th>
                        <th class="text-center"><span>Nome</span></th>
                        <th class="text-center"><span>Email</span></th>
                        <th class="text-center"><span>Contacto</span></th>
                        <th class="text-center"><span>Rating</span></th>
                        <th class="text-center"><span>Turno</span></th>
                        <th class="text-center"><span>Data de Registo</span></th>
                        <th class="text-center">Remover</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ProfessionalsList) {
                        <tr>
                            <td class="text-center">
                                <img src="data:image/jpeg;base64,@System.Convert.ToBase64String(item.Avatar)" width="50" height="50" alt="" />
                                <span><strong> @item.UserName</strong></span>
                            </td>
                            <td class="text-center">@item.Name</td>
                            <td class="text-center">
                                <span>@item.Email</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Contact</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Rating</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Shift</span>
                            </td>
                            <td class="text-center">
                                <span>
                                    @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.RegistrationDate))
                                </span>
                            </td>
                            <td class="text-center" style="width: 15%;">

                                <form asp-page-handler="DeleteProfessional" asp-route-username="@item.UserName" method="post">
                                    <button type="submit" class="myButton">
                                        <span class="fa-stack">
                                            <i class="fa fa-minus-square fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </button>
                                </form>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

@if (Model.WorksList != null) {

    <h4>Lista de Trabalhos</h4>
    <hr />

    <div class="container-fluid">
        <div class="table-responsive">
            <table id="works" class="row-border" style="width:100%">
                <thead>
                    <tr>
                        <th class="text-center"><span>ID</span></th>
                        <th class="text-center"><span>Cliente</span></th>
                        <th class="text-center"><span>Profissional</span></th>
                        <th class="text-center"><span>Preço</span></th>
                        <th class="text-center"><span>Data</span></th>
                        <th class="text-center"><span>Duração</span></th>
                        <th class="text-center"><span>Pagamento</span></th>
                        <th class="text-center"><span>Estado</span></th>
                        <th class="text-center">Marcar como pago</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.WorksList) {
                        <tr>
                            <td class="text-center">
                                <span>@item.Id</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Client.UserName</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Professional.UserName</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Cost €</span>
                            </td>
                            <td class="text-center">
                                <span>@Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.Date))</span>
                            </td>
                            <td class="text-center">
                                <span>@item.Duration horas</span>
                            </td>
                            <td class="text-center">
                                <span class="label label-default">@item.Payment</span>
                            </td>
                            <td class="text-center">
                                <span class="label label-default">@item.Status</span>
                            </td>

                            <td class="text-center" style="width: 15%;">
                                @if (item.Payment.Equals("Não Pago")) {
                                    <form asp-page-handler="MarkAsPaid" asp-route-id="@item.Id" method="post">
                                        <button type="submit" class="myButton">
                                            <span class="fa-stack">
                                                <i class="fa fa-credit-card fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </button>
                                    </form>
                                }
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

GuguDadah/GuguDadah/Pages/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
    var DurationAlert = (string)TempData["_alert.DurationAlert"];
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(function () {
        var alert = $('div.alert[auto-close]');
        alert.each(function () {
            var that = $(this);
            var time_period = that.attr('auto-close');
            setTimeout(function () {
                that.alert('close');
            }, time_period);
        });
    });
</script>



<div class="alert-container">
    @if (!string.IsNullOrEmpty(type)) {
        <div class="alert alert-@type alert-dismissible" auto-close="@DurationAlert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>@title</strong> @body
        </div>
    }
</div>